features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://cone_security_0.png'
favicon:
  use_default: false
  path: 'public://cone.png'
  mimetype: image/png
